registrarsite/registrar/urls.py
from django.conf.urls import url
from . import views

app_name = "registrar"

urlpatterns = [
    # Home page (for log in)
    url(r'^$', views.index, name="home"),
    # POST form to log in users
    url(r'^sign-in/$', views.signin, name="signin"),
    # Dashboard for logged in users
    url(r'^dashboard/?$', views.dashboard, name="dashboard"),
    # Add course page
    url(r'^add-course/?$', views.add_course, name="add_course"),
    # POST form to save course
    url(r'^save-course/?$', views.save_course, name="save_course"),
    # Drop course page
    url(r'^view-course/?$', views.view_course, name="view_course"),
    # Course details page
    url(r'^update-course/(?P<cid>\d+)/?$', views.update_course, name="update_course"),
    # POST form to update course
    url(r'^edit-course/(?P<cid>\d+)/?$', views.edit_course, name="edit_course"),
    # Delete Course
    url(r'^delete_course/(?P<cid>\d+)/?$', views.delete_course, name="delete_course"),
    # View Student Page
    url(r'^view-student/?$', views.view_student, name="view_student"),
    # Update Student Page
    url(r'^update-student/(?P<sid>\d+)/?$', views.update_student, name="update_student"),
    # POST form to edit student information
    url(r'^edit-student/(?P<sid>\d+)/?$', views.edit_student, name="edit_student"),
    # Log out link
    url(r'^log-out/$', views.log_out, name="log_out")
]

registrarsite/registrarsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('registrar.urls'))
]

registrarsite/registrar/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
# Create your models here.

class Course(models.Model):

    SEMESTERS = (
        ("Spring", "Spring"),
        ("Summer", "Summer"),
        ("Fall", "Fall")
    )

    DAYS = (
        ("Monday & Wednesday", "Monday & Wednesday"),
        ("Tuesday & Thursday", "Tuesday & Thursday"),
        ("Friday", "Friday"),
        ("Saturday", "Saturday")
    )
    # TODO: must do a check so that friday/saturday classes only have 3 hour times
    # and mon-thu don't have fri-sat times
    TIMES = (
        ("0900 to 1040", "0900 to 1040"),
        ("1100 to 1240", "1100 to 1240"),
        ("1320 to 1500", "1320 to 1500"),
        ("1530 to 1710", "1530 to 1710"),
        ("1720 to 1900", "1720 to 1900"),
        ("1920 to 2100", "1920 to 2100"),
        ("1330 to 1700", "1330 to 1700"),
        ("1740 to 2100", "1740 to 2100")
    )

    DEPARTMENTS = (
        ("ACT", "ACT"),
        ("APT", "APT"),
        ("IBA", "IBA"),
        ("IR", "IR"),
        ("IST", "IST"),
        ("PHL", "PHL"),
        ("PSY", "PSY")
    )

    course_id = models.CharField(blank=False, max_length=10)
    course_name = models.CharField(blank=False, max_length=50)
    instructor = models.CharField(blank=False, max_length=50)
    semester = models.CharField(blank=False, max_length=10, choices=SEMESTERS)
    year = models.CharField(blank=False, max_length=4,
                            help_text="Please input a valid year when the course will be offered")
    day = models.CharField(blank=False, max_length=20, choices=DAYS)
    time = models.CharField(blank=False, max_length=15, choices=TIMES)
    start_date = models.DateField(blank=False)
    end_date = models.DateField(blank=False)
    location = models.CharField(blank=False, max_length=30)
    department = models.CharField(blank=False, max_length=7, choices=DEPARTMENTS)
    seats = models.IntegerField(blank=False, default=1, validators=[
        MaxValueValidator(100),
        MinValueValidator(0)])
    deleted = models.BooleanField(blank=False, default=False)

    def __str__(self):
        return "{0} - {1} {2} {3}\n{4} {5}".format(self.course_id, self.course_name, self.semester, self.year, self.day,
                                                   self.time)


class Student(models.Model):
    PREFIXES = (
        ("Mr", "Mr"),
        ("Mrs", "Mrs"),
        ("Miss", "Miss")
    )

    GENDERS = (
        ("Female", "Female"),
        ("Male", "Male")
    )

    MARRIAGE_STATUSES = (
        ("Divorced", "Divorced"),
        ("Married", "Married"),
        ("Single", "Single")
    )

    CLASSIFICATIONS = (
        ("Freshman", "Freshman"),
        ("Sophomore", "Sophomore"),
        ("Junior", "Junior"),
        ("Senior", "Senior"),
        ("Graduated", "Graduated"),
        ("Post Graduate", "Post Graduate"),
        ("Doctorate", "Doctorate"),
        ("Leave", "Leave"),
        ("Other", "Other")
    )

    ACADEMIC_STATUSES = (
        ("Good", "Good"),
        ("Disciplinary Action", "Disciplinary Action"),
        ("Suspended", "Suspended"),
        ("Expelled", "Expelled")
    )

    DEGREES = (
        ("Bachelor of Arts", "Bachelor of Arts"),
        ("Bachelor of Science", "Bachelor of Science")
    )

    student_id = models.IntegerField(blank=False, primary_key=True, validators=[
        MinValueValidator(1),
        MaxValueValidator(30000000)     # 30 million
    ])
    prefix = models.CharField(blank=False, max_length=5, choices=PREFIXES)
    first_name = models.CharField(blank=False, max_length=30)
    second_name = models.CharField(blank=True, null=True, max_length=30)        # possible null saved as '' if null
    last_name = models.CharField(blank=False, max_length=30)
    dob = models.DateField(blank=True, null=True)                        # possible null
    gender = models.CharField(blank=False, max_length=6, choices=GENDERS)
    ethnicity = models.CharField(blank=True, null=True, max_length=35)    # possible null saved as '' if null
    email = models.EmailField(blank=True, null=True)                      # possible null
    primary_telephone = models.IntegerField(blank=True, null=True, validators=[
        RegexValidator(r'\d{10,10}', 'Number must be 10 digits', 'Invalid number')
    ])                                                                  # possible null
    secondary_telephone = models.IntegerField(blank=True, null=True, validators=[
        RegexValidator(r'\d{10,10}', 'Number must be 10 digits', 'Invalid number')
    ])                                                                  # possible null
    postal_address = models.CharField(blank=True, null=True, max_length=75)    # possible null saved as '' if null
    marital_status = models.CharField(blank=False, max_length=10, choices=MARRIAGE_STATUSES)
    kin_name = models.CharField(blank=True, null=False, max_length=50)        # possible null saved as '' if null
    kin_email = models.EmailField(blank=True, null=True)                      # possible null
    kin_telephone = models.IntegerField(blank=True, null=True, validators=[
        RegexValidator(r'\d{10,10}', 'Number must be 10 digits', 'Invalid number')
    ])                                                                  # possible null
    classification = models.CharField(blank=False, max_length=15, choices=CLASSIFICATIONS)
    academic_status = models.CharField(blank=False, max_length=20, choices=ACADEMIC_STATUSES)
    enrolled_date = models.DateField(blank=False)
    planned_grad_date = models.DateField(blank=False)
    degree = models.CharField(blank=False, max_length=40, choices=DEGREES)
    major1 = models.CharField(blank=True, null=True, max_length=50)     # possible null saved as '' if null
    major2 = models.CharField(blank=True, null=True, max_length=50)     # possible null saved as '' if null
    minor1 = models.CharField(blank=True, null=True, max_length=50)     # possible null saved as '' if null
    minor2 = models.CharField(blank=True, null=True, max_length=50)     # possible null saved as '' if null
    conc1 = models.CharField(blank=True, null=True, max_length=50)     # possible null saved as '' if null
    conc2 = models.CharField(blank=True, null=True, max_length=50)     # possible null saved as '' if null
    prev_education = models.CharField(blank=False, max_length=100)
    comments = models.TextField(blank=True, null=True, max_length=600)  # possible null saved as '' if null

    def __str__(self):
        return "{0} - {1} {2} {3}".format(self.student_id, self.first_name, self.second_name, self.last_name)

registrarsite/registrar/forms.py
from django import forms
from django.db import models
from django.core.exceptions import ValidationError
from .models import Course, Student


class DateInput(forms.DateInput):
    input_type = "date"


class AddCourseForm(forms.ModelForm):

    # def __init__(self, *args, **kwargs):
    #     super(AddCourseForm, self).__init__(*args, **kwargs)
    #     self.fields["course_id"].required = True
    #     for key in self.fields:
    #         self.fields[key].required = True

    class Meta:
        model = Course
        fields = ("course_id", "course_name", "instructor", "semester", "year", "day", "time", "start_date", "end_date",
                  "location", "department", "seats")
        widgets = {
            "course_id": forms.TextInput(attrs={"placeholder": "e.g APT 2080", "required": "true"}),
            "course_name": forms.TextInput(attrs={"placeholder": "e.g Software Engineering", "required": "true"}),
            "instructor": forms.TextInput(attrs={"placeholder": "e.g Dr. Chege", "required": "true"}),
            "year": forms.TextInput(attrs={"placeholder": "e.g 2016", "required": "true"}),
            "location": forms.TextInput(attrs={"placeholder": "e.g Lab 2", "required": "true"}),
            "seats": forms.TextInput(attrs={"required": "true"}),
            "start_date": DateInput(),
            "end_date": DateInput(),
        }


class EditCourseForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = ("course_id", "course_name", "instructor", "semester", "year", "day", "time", "start_date", "end_date",
                  "location", "department", "seats")
        widgets = {
            "course_id": forms.TextInput(attrs={"required": "true"}),
            "course_name": forms.TextInput(attrs={"required": "true"}),
            "instructor": forms.TextInput(attrs={"required": "true"}),
            "year": forms.TextInput(attrs={"required": "true"}),
            "location": forms.TextInput(attrs={"required": "true"}),
            "seats": forms.TextInput(attrs={"min": "0", "max": "100", "required": "true"}),
            "start_date": DateInput(),
            "end_date": DateInput(),
        }


class UpdateStudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = (
            "student_id",
            "prefix",
            "first_name",
            "second_name",
            "last_name",
            "dob",
            "gender",
            "ethnicity",
            "email",
            "primary_telephone",
            "secondary_telephone",
            "postal_address",
            "marital_status",
            "kin_name",
            "kin_email",
            "kin_telephone",
            "classification",
            "academic_status",
            "enrolled_date",
            "planned_grad_date",
            "degree",
            "major1",
            "major2",
            "minor1",
            "minor2",
            "conc1",
            "conc2",
            "prev_education",
            "comments"
        )
        # prefix, gender, phone missing from widgets because it changes to text
        widgets = {
            "student_id": forms.TextInput(attrs={"required": "true", "readonly": "true", "disabled": "true"}),
            "first_name": forms.TextInput(attrs={"required": "true", "placeholder": "First Name"}),
            "second_name": forms.TextInput(attrs={"placeholder": "Second Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "dob": DateInput(),
            "email": forms.TextInput(attrs={"placeholder": "example@email.com"}),
            "kin_email": forms.TextInput(attrs={"placeholder": "example@email.com"}),
            "enrolled_date": DateInput(),
            "planned_grad_date": DateInput(),
            "major1": forms.TextInput(attrs={"placeholder": "e.g. APT"}),
            "minor1": forms.TextInput(attrs={"placeholder": "e.g. PSY"}),
            "conc1": forms.TextInput(attrs={"placeholder": "e.g. Networking"}),
        }

registrarsite/registrar/templates/registrar/add-course.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'registrar/style.css' %}"/>
        <title>Add Course | USIU Registrar</title>
    </head>
    <body>
        <div class="page-header">
            <h2>USIU Africa Registrar Portal</h2>
        </div>
        <nav class="nav-bar">
            <a class="menu-item" href="{% url 'registrar:dashboard' %}">Dashboard</a>
            <a class="menu-item" href="{% url 'registrar:add_course' %}">Add Course</a>
            <a class="menu-item" href="{% url 'registrar:view_course' %}">View Course</a>
            <a class="menu-item" href="{% url 'registrar:view_student' %}">View Student</a>
            <a class="menu-item" href="{% url 'registrar:log_out' %}">Log Out</a>
        </nav>
        <h2 class="content-header">Add Course</h2><hr>
        {% if messages %}
        {% for message in messages %}
        <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
        <br><hr><br>
        {% endif %}
        <form  id="add-course-container" action="{% url 'registrar:save_course' %}" method="POST">
            {% csrf_token %}
            <div class="add-fieldset">
                <label for="id_course_id">Course ID </label> {{ form.course_id }} <br><br>
            </div>
            <div class="add-fieldset">
                <label for="id_course_name">Course Name </label> {{ form.course_name }} <br><br>
            </div>
            <div class="add-fieldset">
                <label for="id_instructor">Instructor </label> {{ form.instructor }} <br><br>
            </div>
            <div class="add-fieldset">
                <label for="id_semester">Semester </label> {{ form.semester }} <br><br>
            </div>
            <div class="add-fieldset">
                <label for="id_year">Year </label> {{ form.year }} <br><br>
            </div>
            <div class="add-fieldset">
                <label for="id_day">Day </label> {{ form.day }} <br><br>
            </div>
            <div class="add-fieldset">
                <label for="id_time">Time </label> {{ form.time }} <br><br>
            </div>
            <div class="add-fieldset">
                <label for="id_start_date">Start Date </label> {{ form.start_date }} <br><br>
            </div>
            <div class="add-fieldset">
                <label for="id_end_date">End Date </label> {{ form.end_date }} <br><br>
            </div>
            <div class="add-fieldset">
                <label for="id_location">Location </label> {{ form.location }} <br><br>
            </div>
            <div class="add-fieldset">
                <label for="id_department">Department </label> {{ form.department }} <br><br>
            </div>
            <div class="add-fieldset">
            <label for="id_seats">Seats </label> {{ form.seats }} <br><br>
            </div>
            <div class="add-fieldset">
                <input type="submit" id="add-button" value="Add Course"/><br><br>
            </div>
        </form>
    </body>
</html>

registrarsite/registrar/templates/registrar/dashboard.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'registrar/style.css' %}"/>
        <title>Dashboard | USIU Registrar</title>
    </head>
    <body>
        <div class="page-header">
            <h2>USIU Africa Registrar Portal</h2>
        </div>
        <nav class="nav-bar">
            <a class="menu-item" href="{% url 'registrar:dashboard' %}">Dashboard</a>
            <a class="menu-item" href="{% url 'registrar:add_course' %}">Add Course</a>
            <a class="menu-item" href="{% url 'registrar:view_course' %}">View Course</a>
            <a class="menu-item" href="{% url 'registrar:view_student' %}">View Student</a>
            <a class="menu-item" href="{% url 'registrar:log_out' %}">Log Out</a>
        </nav>
        <h2 class="content-header">Welcome <span id="username-color">{{ request.user }}</span></h2><hr>
        {% if messages %}
        {% for message in messages %}
             <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
        {% endif %}

        {% if request.user.last_login %}
        <br><hr>
        <span class="info">Your last log in was: {{ request.user.last_login }}</span>
        <br>
        {% endif %}
    </body>
</html>

registrarsite/registrar/templates/registrar/update-course.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'registrar/style.css' %}"/>
        <title>Update Course | USIU Registrar</title>
    </head>
    <body>
        <div class="page-header">
            <h2>USIU Africa Registrar Portal</h2>
        </div>
        <nav class="nav-bar">
            <a class="menu-item" href="{% url 'registrar:dashboard' %}">Dashboard</a>
            <a class="menu-item" href="{% url 'registrar:add_course' %}">Add Course</a>
            <a class="menu-item" href="{% url 'registrar:view_course' %}">View Course</a>
            <a class="menu-item" href="{% url 'registrar:view_student' %}">View Student</a>
            <a class="menu-item" href="{% url 'registrar:log_out' %}">Log Out</a>
        </nav>
        <h2 class="content-header">Update Course {% if id %} {{ id }} {% endif %}</h2><hr>
        {% if messages %}
        {% for message in messages %}
        <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
        <br><hr><br>
        {% endif %}
        <form  id="update-course-container" action="{% url 'registrar:edit_course' cid=id %}" method="POST">
            {% csrf_token %}
            <div id="primary-course-info">
                <h3 class="update-section-title">Primary Information</h3><br><br><br><br>
                <div class="update-fieldset"><label for="id_course_id">Course ID </label> {{ form.course_id }}<div class="update-right"><label for="id_course_name">Course Name </label> {{ form.course_name }} <br><br></div> </div>
                <div class="update-fieldset"><label for="id_instructor">Instructor </label> {{ form.instructor }} <br><br></div>
                <div class="update-fieldset"><label for="id_semester">Semester </label> {{ form.semester }} <label for="id_year">Year </label> {{ form.year }} <br><br></div>
                <div class="update-fieldset"><label for="id_day">Day </label> {{ form.day }} <div class="update-right"><label for="id_time">Time </label> {{ form.time }} <br><br></div></div>
            </div>
            <div id="secondary-course-info">
                <br><br><h3 class="update-section-title">Secondary Information</h3><br><br><br><br><br><br>
                <div class="update-fieldset"><label for="id_start_date">Start Date </label> {{ form.start_date }} <div class="update-right"><label for="id_end_date">End Date </label> {{ form.end_date }} <br><br></div></div>
                <div class="update-fieldset"><label for="id_location">Location </label> {{ form.location }} <br><br></div>
                <div class="update-fieldset"><label for="id_department">Department </label> {{ form.department }} <br><br></div>
                <div class="update-fieldset"><label for="id_seats">Seats </label> {{ form.seats }} <br><br></div>
            </div><br><br>
            <a id="delete-course-link" href="{% url 'registrar:delete_course' cid=id %}">Delete Course</a><br><br>
            <input type="submit" id="update-button" value="Update Course"/><br><br>
        </form>
    </body>
</html>

registrarsite/registrar/templates/registrar/update-student.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'registrar/style.css' %}"/>
        <title>Update Student | USIU Registrar</title>
    </head>
    <body>
        <div class="page-header">
            <h2>USIU Africa Registrar Portal</h2>
        </div>
        <nav class="nav-bar">
            <a class="menu-item" href="{% url 'registrar:dashboard' %}">Dashboard</a>
            <a class="menu-item" href="{% url 'registrar:add_course' %}">Add Course</a>
            <a class="menu-item" href="{% url 'registrar:view_course' %}">View Course</a>
            <a class="menu-item" href="{% url 'registrar:view_student' %}">View Student</a>
            <a class="menu-item" href="{% url 'registrar:log_out' %}">Log Out</a>
        </nav>
        <h2 class="content-header">Update Student Information</h2><hr>
        {% if messages %}
        {% for message in messages %}
        <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
        <br><hr>
        {% endif %}
        {% if form %}
        <form id="update-student-form" action="{% url 'registrar:edit_student' sid=id %}" method="POST">
            {% csrf_token %}
            <div id="student-name-info">
                <label for="id_student_id">&nbsp;</label> {{ form.student_id }} <label for="id_prefix">&nbsp;</label> {{ form.prefix }} <label for="id_first_name">&nbsp; </label> {{ form.first_name }} <label for="id_second_name">&nbsp; </label> {{ form.second_name }} <label for="id_last_name">&nbsp; </label> {{ form.last_name }} <br><br>
            </div>
            <div id="student-personal-info">
                <span class="student-update-section-header">Personal Information</span><br>
                <fieldset>
                    <label for="id_dob">Date Of Birth </label> {{ form.dob }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_gender">Gender </label>{{ form.gender }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_ethnicity">Ethnicity </label> {{ form.ethnicity }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_marital_status">Marital Status </label> {{ form.marital_status }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_email">Email </label> {{ form.email }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_primary_telephone">Primary Telephone Number </label> {{ form.primary_telephone }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_secondary_telephone">Secondary Telephone Number </label> {{ form.secondary_telephone }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_postal_address">Postal Address </label> {{ form.postal_address }} <br><br>
                </fieldset>
            </div>
            <div id="student-academic-info">
                <span class="student-update-section-header">Academic Information</span><br>
                <fieldset>
                    <label for="id_classification">Classification </label> {{ form.classification }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_academic_status">Academic Status </label> {{ form.academic_status }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_enrolled_date">Enrolled Date </label> {{ form.enrolled_date }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_planned_grad_date">Planned Graduation Date </label> {{ form.planned_grad_date }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_degree">Degree </label> {{ form.degree }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_major1">First Major </label> {{ form.major1 }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_major2">Second Major </label>  {{ form.major2 }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_minor1">First Minor </label> {{ form.minor1 }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_minor2">Second Minor </label> {{ form.minor2 }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_conc1">First Concentration </label> {{ form.conc1 }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_conc2">Second Concentration </label> {{ form.conc2 }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_prev_education">Previous education:</label> {{ form.prev_education }} <br><br>
                </fieldset>
            </div>
            <div id="student-kin-info">
                <span class="student-update-section-header">Other Information</span><br>
                <fieldset>
                    <label for="id_kin_name">Next of Kin Name </label> {{ form.kin_name }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_kin_email">Next of Kin Email </label> {{ form.kin_email }} <br><br>
                </fieldset>
                <fieldset>
                    <label for="id_kin_telephone">Next of Kin Telephone Number </label> {{ form.kin_telephone }} <br><br>
                </fieldset>
            </div>
            <div id="student-other-info">
                <span class="student-update-section-header">Comments</span><br>
                <fieldset>
                    <label for="id_comments">Comments </label> <br>
                    {{ form.comments }} <br><br>
                </fieldset>
            </div>
            <input type="submit" id="update-student-button" value="Update Student" />
        </form>
        <br><br>
        {% else %}
        <span class="info">There was a problem retrieving the form. Please refresh the page</span>
        {% endif %}
    <br><br>
    </body>
</html>

registrarsite/registrar/templates/registrar/view-course.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'registrar/style.css' %}"/>
        <title>View Course | USIU Registrar</title>
    </head>
    <body>
        <div class="page-header">
            <h2>USIU Africa Registrar Portal</h2>
        </div>
        <nav class="nav-bar">
            <a class="menu-item" href="{% url 'registrar:dashboard' %}">Dashboard</a>
            <a class="menu-item" href="{% url 'registrar:add_course' %}">Add Course</a>
            <a class="menu-item" href="{% url 'registrar:view_course' %}">View Course</a>
            <a class="menu-item" href="{% url 'registrar:view_student' %}">View Student</a>
            <a class="menu-item" href="{% url 'registrar:log_out' %}">Log Out</a>
        </nav>
        <h2 class="content-header">View Course</h2><hr>
        <br>
        <form action="{% url 'registrar:view_course' %}" method="POST">
            {% csrf_token %}
            <input class="course_search" type="text" id="semester" name="semester" maxlength="10" title="E.g. Summer, Spring or Fall" placeholder="Semester" required />
            <input class="course_search" type="text" id="year" name="year" maxlength="4" title="E.g. 2016" placeholder="Year" required/>
            <input class="course_search" type="text" id="course-code" name="course-code" maxlength="15" title="E.g. APT 1050" placeholder="Course Code"/>
            <input type="submit" id="course-search-button" value="Find"/><br><br>
            <label for="include_deleted">Include Deleted Courses</label> <input type="checkbox" name="include_deleted" id="include_deleted" title="Include deleted courses?"/>
        </form>
        <br><hr>
        {% if messages %}
        {% for message in messages %}
        <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
        <br><hr>
        {% endif %}

        {% if results %}
        <br><hr>
        <table>
            <tr>
                <th>Course ID</th>
                <th>Course Name</th>
                <th>Days</th>
                <th>Time</th>
                <th>More</th>
            </tr>
            <tr class="course-results">
                {% for result in results %}
                <td>{{ result.course_id }}</td>
                <td>{{ result.course_name }}</td>
                <td>{{ result.day }}</td>
                <td>{{ result.time }}</td>
                <td><form action="{% url 'registrar:update_course' cid=result.id %}" method="POST">{% csrf_token %}<input type="submit" value="Details"/></form></td>
                {% endfor %}
            </tr>
        </table>
        <br><hr>
        {% endif %}
    </body>
</html>

registrarsite/registrar/templates/registrar/view-student.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'registrar/style.css' %}"/>
        <title>View Student Information | USIU Registrar</title>
    </head>
    <body>
        <div class="page-header">
            <h2>USIU Africa Registrar Portal</h2>
        </div>
        <nav class="nav-bar">
            <a class="menu-item" href="{% url 'registrar:dashboard' %}">Dashboard</a>
            <a class="menu-item" href="{% url 'registrar:add_course' %}">Add Course</a>
            <a class="menu-item" href="{% url 'registrar:view_course' %}">View Course</a>
            <a class="menu-item" href="{% url 'registrar:view_student' %}">View Student</a>
            <a class="menu-item" href="{% url 'registrar:log_out' %}">Log Out</a>
        </nav>
        <h2 class="content-header">View Student</h2><hr>
        <form action="{% url 'registrar:view_student' %}" method="POST">
            {% csrf_token %}
            <label id="student-id-label" for="student_id">Student ID </label> <input type="number" id="student_id" name="student_id" min="0" max="30000000" required/>
            <input type="submit" id="find-student-button" value="Find Student"/>
        </form>
        <br><hr>
        {% if messages %}
        {% for message in messages %}
        <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
        <br><hr>
        {% endif %}
    </body>
</html>